language: Fortran
rvm:
  - 2.1.0
script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq build-dep make
  - sudo apt-get -qq install gfortran-$MY_FC_V libatlas3-base &
  - export MY_ERB=erb
  - export MY_FC=/usr/bin/gfortran-$MY_FC_V
  - readonly ext_dir=_tmp_
  - mkdir -p $ext_dir
  - pushd $ext_dir
  - wget http://ftp.gnu.org/gnu/make/$MAKE_V.tar.gz
  - tar xf $MAKE_V.tar.gz
  - pushd $MAKE_V
  - ./configure
  - make -j$(nproc)
  - popd
  - popd
  - wait
  - $MY_FC --version
  - readonly make=$ext_dir/$MAKE_V/make
  - nproc
  - $make --version
  - nproc
  - $make -j$(nproc) all check
env:
  - MY_FC_V=4.9 MAKE_V=make-3.82
  - MY_FC_V=4.9 MAKE_V=make-4.1
  - MY_FC_V=5 MAKE_V=make-3.82
  - MY_FC_V=5 MAKE_V=make-4.1
