language: fortran
sudo: required
dist: trusty
rvm:
  - 1.9.3
  - 2.1.7
  - 2.2.3
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-4.9
      - gfortran-5
      - make
      - liblapack-dev
script:
  - readonly ext_dir=_tmp_
  - mkdir -p $ext_dir
  - pushd $ext_dir
  - wget http://ftp.gnu.org/gnu/make/$MAKE_V.tar.gz
  - tar xf $MAKE_V.tar.gz
  - pushd $MAKE_V
  - ./configure
  - make -j$(nproc)
  - ulimit -a
  - popd
  - popd
  - wait
  - readonly make=$ext_dir/$MAKE_V/make
  - make --version
  - $make --version
  - export MY_ERB=erb
  - export MY_FC=gfortran-$MY_FC_V
  - $MY_FC --version
  - nproc
  - $make -k -j1 all check ERB="$MY_ERB" FC="$MY_FC"
env:
  - MY_FC_V=4.9 MAKE_V=make-3.82
  - MY_FC_V=5 MAKE_V=make-3.82
  - MY_FC_V=4.9 MAKE_V=make-4.1
  - MY_FC_V=5 MAKE_V=make-4.1
