language: Fortran
rvm:
  - 2.1.0
before_install:
  - sudo apt-get update
  - sudo apt-get -qq install gcc-snapshot git
script:
  - $MY_FORTRAN --version
  - make
  - make check
env:
  - MY_ERB=erb MY_FC="/usr/lib/gcc-snapshot/bin/gfortran"
